ENABLE_REMOTE_ALERTS = True

API_URL = "http://127.0.0.1:3005/api/alertas"
API_TOKEN = "123456789abcdef"

VEICULO_ID = "VEICULO_001"
MOTORISTA_ID = "MOTORISTA_001"
DISPOSITIVO_ID = "RASPBERRY_001"

SQLITE_DB_PATH = "database/alertas_local.db"

REMOTE_ALERT_LEVELS = [
    "ALERTA_SONOLENCIA",
    "ALERTA_DISTRACAO",
    "CRITICO"
]

API_COOLDOWN_SECONDS = 60
SYNC_INTERVAL_SECONDS = 15
REQUEST_TIMEOUT_SECONDS = 5